apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess
spec:
  template:
    spec:
      initContainers:
      - name: pingaccess-discovery-service
        image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/amazon/aws-cli:2.0.17
        imagePullPolicy: IfNotPresent
        command:
        - /get_ssm_env_vars.sh
        envFrom:
        - configMapRef:
            name: pingaccess-environment-variables
        volumeMounts:
        - name: data-dir
          mountPath: /config
        - name: discovery-service
          mountPath: /get_ssm_env_vars.sh
          subPath: get_ssm_env_vars.sh
      volumes:
      - name: discovery-service
        configMap:
          name: discovery-service
          defaultMode: 0555
