kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../../../base/ingress/nginx/public

patchesStrategicMerge:
- |-
  apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: nginx-ingress-controller
  spec:
    minReplicas: 4
    maxReplicas: 6
    targetCPUUtilizationPercentage: 50

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nginx-configuration
    namespace: ingress-nginx-public
  data:
    main-snippet: load_module /usr/lib/nginx/modules/ngx_http_sigsci_module.so;
    keep-alive-requests: "100000"
    upstream-keepalive-timeout: "30"
    max-worker-connections: "0"
    worker-processes: "4"
