kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/cert-manager?ref=${K8S_GIT_BRANCH}

patchesStrategicMerge:

### Lets encrypt ACME certificate issuer for the cluster ###
- |-
  apiVersion: cert-manager.io/v1alpha2
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-prod
  spec:
    acme:
      server: ${LETS_ENCRYPT_SERVER}
      email: ${CLUSTER_NAME_LC}@${DNS_ZONE}
      solvers:
      - dns01:
          route53:
            region: ${REGION}
        selector:
          dnsZones:
          - ${DNS_ZONE}

### Lets encrypt ACME certificate for all endpoints ###
- |-
  apiVersion: cert-manager.io/v1alpha2
  kind: Certificate
  metadata:
    name: acme-tls-cert
    namespace: cert-manager
  spec:
    dnsNames:
    - '*.${DNS_ZONE}'

patchesJson6902:

# Change the namespace of the ACME certificate to the ping-cloud namespace
- target:
    group: cert-manager.io
    version: v1alpha2
    kind: Certificate
    name: acme-tls-cert
    namespace: cert-manager
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ${PING_CLOUD_NAMESPACE}