# This defines the private ingress for the pingfederate admin services.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingfederate-admin-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-private
spec:
  tls:
    - hosts:
        - pingfederate-admin-api-dev.ping-demo.com
  rules:
    - host: pingfederate-admin-api-dev.ping-demo.com
      http:
        paths:
          # This rule gives internal access to the pingfederate admin services.
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pingfederate-admin
                port:
                  name: pf-admin
