apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdelegator
spec:
  template:
    spec:
      containers:
      - name: pingdelegator
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "1"