- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --ingress-class=nginx-public
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --controller-class=k8s.io/ingress-nginx-public
