kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- namespace.yaml
- ../base
- rbac.yaml
- hpa.yaml

namespace: ingress-nginx-public

commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: ingress-nginx
  app.kubernetes.io/role: ingress-nginx-public

patchesJson6902:
- path: add-deployment-args.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
- path: add-owasp-annotations.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
- path: add-sigsci-sidecar.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
- path: add-sigsci-configmap.yaml
  target:
    group: ""
    version: v1
    kind: ConfigMap
    name: nginx-configuration
