kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingdirectory

resources:
- storage.yaml
- statefulset.yaml
- service.yaml
- ingress.yaml
- disruption-budget.yaml

patchesStrategicMerge:
- pingdirectory-tunnel.yaml