# Sets up the storage class for the pingdirectory servers (data and configuration)

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingdirectory-io1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  fsType: ext4
  iopsPerGB: "50"
mountOptions:
  - discard
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingdirectory-gp2
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
mountOptions:
  - discard
allowVolumeExpansion: true