# A manual backup job - this does the same thing as the CronJob except it may be configured to be triggered in reaction
# to a ClickOps event.
apiVersion: batch/v1
kind: Job
metadata:
  name: pingdirectory-backup
  labels:
    app: ping-cloud
    role: pingdirectory
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 5
  template:
    spec:
      serviceAccount: ping-serviceaccount
      restartPolicy: Never
      containers:
      - name: pingdirectory-backup
        image: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingdirectory:8.3.0.0-v1.0.21
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
        command:
        - /opt/in/backup.sh
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
        volumeMounts:
        - name: backup-script
          mountPath: /opt/in/backup.sh
          subPath: backup.sh
      volumes:
      - name: backup-script
        configMap:
          name: pingdirectory-backup
          defaultMode: 0555
