apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-backup-cronjob
data:
  backup-cronjob.sh: |-
    #!/bin/sh

    # Install kubectl
    curl -sS https://storage.googleapis.com/kubernetes-release/release/"${KUBECTL_VERSION}"/bin/linux/amd64/kubectl \
    -o /tmp/kubectl
    chmod +x /tmp/kubectl

    # Execute backup-ops.sh script (which kicks off the k8s pingdirectory-backup Job)
    SCRIPT="/opt/in/backup-ops.sh"
    test -x ${SCRIPT} && ${SCRIPT} "scheduled-cronjob"

---

# Do a full backup of the user backend every 6 hours.
# A manual restore can be performed using the restore job (restore.yaml) when
# necessary.

apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingdirectory-periodic-backup
spec:
  schedule: "30 */6 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 90
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: ping-serviceaccount
          restartPolicy: OnFailure
          containers:
          - name: pingdirectory-backup
            image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-apps/pingdirectory:pdo-6494
            imagePullPolicy: Always
            securityContext:
              runAsGroup: 9999
              runAsNonRoot: true
              runAsUser: 9031
              allowPrivilegeEscalation: false
            command:
            - /opt/in/backup-cronjob.sh
            envFrom:
            - configMapRef:
                name: pingdirectory-environment-variables
            - configMapRef:
                name: pingcommon-environment-variables
            env:
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
            - name: PING_CLOUD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            volumeMounts:
            - name: backup-cronjob-script
              mountPath: /opt/in/backup-cronjob.sh
              subPath: backup-cronjob.sh
            - name: backup-ops-script
              mountPath: /opt/in/backup-ops.sh
              subPath: backup-ops.sh
            - name: pingdirectory-init
              mountPath: /opt/in/hooks/logger.lib.sh
              subPath: logger.lib.sh
          securityContext:
            fsGroup: 9999
          volumes:
          - name: backup-cronjob-script
            configMap:
              name: pingdirectory-backup-cronjob
              defaultMode: 0555
          - name: backup-ops-script
            configMap:
              name: pingdirectory-backup-ops-template-files
              items:
              - key: backup-ops.sh
                path: backup-ops.sh
              defaultMode: 0555
          - name: pingdirectory-init
            configMap:
              name: pingcommon-init
              defaultMode: 0555