apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingdirectory-periodic-export-ldif
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 90
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccount: ping-serviceaccount
          restartPolicy: OnFailure
          containers:
          - name: pingdirectory-periodic-export-ldif
            image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-apps/pingdirectory:pdo-6494
            imagePullPolicy: Always
            securityContext:
              runAsGroup: 9999
              runAsNonRoot: true
              runAsUser: 9031
              allowPrivilegeEscalation: false
            command:
            - /opt/in/export-ldif-data.sh
            env:
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
            envFrom:
            - configMapRef:
                name: pingdirectory-environment-variables
            - configMapRef:
                name: pingcommon-environment-variables
            volumeMounts:
            - name: pingdirectory-export-ldif
              mountPath: /opt/in/export-ldif-data.sh
              subPath: export-ldif-data.sh
          securityContext:
            fsGroup: 9999
          volumes:
          - name: pingdirectory-export-ldif
            configMap:
              name: pingdirectory-export-ldif
              defaultMode: 0555
