kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/git-ops?ref=${K8S_GIT_BRANCH}
- argo-application.yaml

patchesStrategicMerge:

### Update the ArgoCD polling interval ###
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: argocd-application-controller
    namespace: argocd
  spec:
    template:
      spec:
        containers:
        - name: argocd-application-controller
          env:
          - name: APP_RESYNC_SECONDS
            value: "60"

### Known hosts file for cloning the cluster state repo over SSH ###
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-ssh-known-hosts-cm
    namespace: argocd
  data:
    ssh_known_hosts: |-
      ${KNOWN_HOSTS_CLUSTER_STATE_REPO}

patchesJson6902:

### Cluster state repo URL and auth configuration for the CD tool ###
- target:
    version: v1
    kind: ConfigMap
    name: argocd-cm
    namespace: argocd
  patch: |
    - op: add
      path: /data/repositories
      value: |
        - url: ${CLUSTER_STATE_REPO_URL}
          type: git
          sshPrivateKeySecret:
            name: argo-git-deploy
            key: identity
    - op: add
      path: /data/timeout.reconciliation
      value: ${APP_RESYNC_SECONDS}s
