apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-secrets-reader
rules:
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - get
    - list
    - watch
    