kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingcommon-init
  files:
  - scripts/copy-dependencies.sh
  - scripts/wait-for-services.sh
  - scripts/wait-for-pds.sh
  - scripts/utils.lib.sh
  - scripts/logger.lib.sh
- name: pingcommon-environment-variables
  envs:
  - env_vars

resources:
- namespace.yaml
- cluster-rbac.yaml
- rbac.yaml
- secret.yaml
- configmap.yaml
- pingcloud-healthcheck
- pingcloud-metadata