apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-serviceaccount

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pingaccess-serviceaccount

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pingdirectory-serviceaccount

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pingfederate-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ping-role
rules:
  - apiGroups:
    - "batch"
    resources:
    - "jobs"
    verbs:
    - get
    - create
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - delete
    - create
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - "pods"
    - "pods/log"
    - "secrets"
    - "configmaps"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - "persistentvolumeclaims"
    verbs:
    - delete
    - get
    - create
  - apiGroups:
    - ""
    - "apps"
    resources:
    - "statefulsets"
    - "deployments"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - "pods/exec"
    verbs:
    - create
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ping-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-role
subjects:
  - kind: ServiceAccount
    name: ping-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pingaccess-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-role
subjects:
  - kind: ServiceAccount
    name: pingaccess-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pingdirectory-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-role
subjects:
  - kind: ServiceAccount
    name: pingdirectory-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pingfederate-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-role
subjects:
  - kind: ServiceAccount
    name: pingfederate-serviceaccount
