apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcommon-passwords
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
data:
  PF_LDAP_PASSWORD: MkZlZGVyYXRlTTByZQ==
  PF_ADMIN_USER_PASSWORD: MkZlZGVyYXRlTTByZQ==
  DA_OAUTH_TOKEN_VALIDATOR_SECRET: MkZlZGVyYXRlTTByZQ==
  PC_ADMIN_USER_PASSWORD: MkZlZGVyYXRl
  ACME_CERT_KEYSTORE_PASSWORD: MkZlZGVyYXRlTTByZQ==

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
  annotations:
    sealedsecrets.bitnami.com/managed: "true"

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: newrelic-license-key
  annotations:
    sealedsecrets.bitnami.com/managed: "true"

---