kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: p14c-oauth-service

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: p14c-oauth-service-environment-variables

resources:
- deployment.yaml
- rbac.yaml
