kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services