kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- secret-license.yaml
- secret-passwords.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingcentral-environment-variables
  envs:
  - env_vars