kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: postgres-operator

commonLabels:
  app: ping-cloud

resources:
- postgres.yaml

images:
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-postgres
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-pgbackrest
  - name: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter
    newName: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres-exporter
