# NOTE: image and postgres version will need to updated manually according to support in the
# postgres-operator-examples repo: https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/postgres/postgres.yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pf-provisioning
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-0
  postgresVersion: 14
  metadata:
    labels:
      role: pf-provisioning
  instances:
    - name: instance1
      replicas: 3
      minAvailable: 1
      resources:
        requests:
          cpu: 2
          memory: 2Gi
      dataVolumeClaimSpec:
        storageClassName: pgo-gp3
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - pf-provisioning
                topologyKey: "topology.kubernetes.io/zone"
  users:
    # Service account used by PingFederate
    - name: pf-service
      databases:
        - pf-provisioning
    # Account used by Ping Beluga Ops team
    - name: ping-beluga-ops
      databases:
        - pf-provisioning
      options: "SUPERUSER"
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.40-0
      global:
        repo1-path: /pingfederate/provisioning
        # Allow storage solution to handle retention (retain max from PGO perspective)
        repo1-retention-full: "256"
      # Manual backup option allows easy one-off backups via annotation
      # See: https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backup-management/
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
      - name: repo1
        # S3 configuration & schedule set via patches
      # Manual restore option. Needs custom-patch to execute.
      restore:
        enabled: true
        repoName: repo1
        options:
          - --type=default
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.2.0-0
