apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pf-provisioning
spec:
  # NOTE: image and postgres version will need to updated manually accordingly in order to support in the
  # postgres-operator-examples repo: https://github.com/CrunchyData/postgres-operator-examples/blob/main/kustomize/postgres/postgres.yaml
  image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres:ubi8-14.7-0
  # We can choose a Postgres version independently from PGO (so long as it's supported)
  # Here we keep the version at 14 so existing customers aren't doing a major version upgrade in addition to PGO upgrade
  postgresVersion: 14
  metadata:
    labels:
      role: pf-provisioning
  instances:
    - name: instance1
      metadata:
        annotations:
          # This annotation is required to prevent volume-autoscaler to resize this volume
          volume.autoscaler.kubernetes.io/ignore: "true"
      replicas: 3
      minAvailable: 1
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 2
          memory: 2Gi
      dataVolumeClaimSpec:
        storageClassName: pgo-gp3
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - pf-provisioning
                topologyKey: "topology.kubernetes.io/zone"
  users:
    # Service account used by PingFederate
    - name: pf-service
      databases:
        - pf-provisioning
    # Account used by Ping Beluga Ops team
    - name: ping-beluga-ops
      databases:
        - pf-provisioning
      options: "SUPERUSER"
  backups:
    pgbackrest:
      # NOTE: As above, must be manually updated
      image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-pgbackrest:ubi8-2.41-4
      global:
        repo1-path: /pingfederate/provisioning
        # Allow storage solution to handle retention (retain max from PGO perspective)
        repo1-retention-full: "256"
      # Manual backup option allows easy one-off backups via annotation
      # See: https://access.crunchydata.com/documentation/postgres-operator/v5/tutorial/backup-management/
      manual:
        repoName: repo1
        options:
         - --type=full
      jobs:
        ttlSecondsAfterFinished: 60 # Minimum is 60
      repos:
      - name: repo1
        # S3 configuration & schedule set via patches
      # Manual restore option. Needs custom-patch to execute.
      restore:
        enabled: true
        repoName: repo1
        options:
          - --type=default
  monitoring:
    pgmonitor:
      exporter:
        # NOTE: As above, must be manually updated
        image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/crunchydata/crunchy-postgres-exporter:ubi8-5.3.1-0
