apiVersion: batch/v1
kind: Job
metadata:
  name: pingfederate-admin-configurator
spec:
  template:
    spec:
      serviceAccount: pf-script-serviceaccount
      containers:
      - name: pingfederate-admin-configurator
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/p14c-integration:v1.0.36
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: pingfederate-admin-environment-variables
        - secretRef:
            name: pingcommon-passwords
        command: [ 'python3', '-u', '/app/pingfederate_admin_configurator.py' ]
      restartPolicy: Never
  backoffLimit: 4