# create configmap for cluster name and aws region for CloudWatch Logs
# need to replace the placeholders cluster_name and region_name
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nr-license-key
  annotations:
    sealedsecrets.bitnami.com/managed: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-info
data:
  cluster.name: cluster_name
  logs.region: region_name
  log.level: "error"
  read.head: "True"
  read.tail: "Off"
  newrelic_cluster_name: cluster_name
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-role
subjects:
  - kind: ServiceAccount
    name: fluent-bit

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/amazon/aws-for-fluent-bit:2.31.7
        imagePullPolicy: Always
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "S3_BUCKET_NAME=${S3_BUCKET#s3://} /entrypoint.sh"
        securityContext:
          capabilities:
            drop:
              - ALL
            add:
              - CAP_FOWNER
        env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-info
                  key: logs.region
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-info
                  key: cluster.name
            - name: READ_FROM_HEAD
              valueFrom:
                configMapKeyRef:
                  name: cluster-info
                  key: read.head
            - name: READ_FROM_TAIL
              valueFrom:
                configMapKeyRef:
                  name: cluster-info
                  key: read.tail
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FLB_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: cluster-info
                  key: log.level
            - name: NR_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: nr-license-key
                  key: NEW_RELIC_LICENSE_KEY
            - name: S3_BUCKET
              valueFrom:
                  configMapKeyRef:
                    name: s3-raw-logs-bucket
                    key: bucketName
            - name: NR_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-info
                  key: newrelic_cluster_name
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/health
            port: 2020
          initialDelaySeconds: 20
          periodSeconds: 180
          timeoutSeconds: 5
        readinessProbe:
          initialDelaySeconds: 10
          failureThreshold: 3
          httpGet:
            path: /
            port: 2020
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 100Mi
        ports:
          - containerPort: 2020
            name: metrics
        volumeMounts:
        # Please don't change below read-only permissions
        - name: fluentbitstate
          mountPath: /fluent-bit/state
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: runlogjournal
          mountPath: /run/log/journal
          readOnly: true
        - name: dmesg
          mountPath: /var/log/dmesg
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: fluentbitstate
        hostPath:
          path: /fluent-bit/state
        #emptyDir: {}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: runlogjournal
        hostPath:
          path: /run/log/journal
      - name: dmesg
        hostPath:
          path: /var/log/dmesg
      serviceAccountName: fluent-bit
      priorityClassName: system-node-critical
      tolerations:
      - key: node-role.kubernetes.io/controlplane
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
---
kind: Service
apiVersion: v1
metadata:
  name: fluent-bit
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    k8s-app: fluent-bit
  ports:
    - port: 2020
      name: api