kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply PingCentral deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingcentral/server?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingcentral
  newTag: ${PINGCENTRAL_IMAGE_TAG}

generatorOptions:
  disableNameSuffixHash: true

patchesJson6902:

### PingCentral Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: Deployment
    name: pingcentral
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingcentral-last-update-config

### Ingress patches ###

# PingCentral HTTP
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingcentral-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingcentral.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingcentral.${DNS_ZONE}
