apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-reaper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-reaper
  template:
    metadata:
      labels:
        app: pod-reaper
    spec:
      serviceAccountName: pod-reaper-service-account
      containers:
        - name: reaper
          image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/pod-reaper:2.12.0
          resources:
            limits:
              cpu: 30m
              memory: 30Mi
            requests:
              cpu: 20m
              memory: 20Mi
          env:
            - name: REQUIRE_LABEL_KEY
              value: pod-reaper
            - name: REQUIRE_LABEL_VALUES
              value: enabled
            - name: POD_SORTING_STRATEGY
              value: "oldest-first"
            - name: EVICT
              value: "true"
          envFrom:
            - configMapRef:
                name: pod-reaper-environment-variables