kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: pod-reaper

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:
- name: pod-reaper-environment-variables
  envs:
  - env_vars

resources:
- deployment.yaml
- namespace.yaml
- rbac.yaml