# This priority class was added because when scaling-up a CI/CD cluster a lot of resources are deployed to very few
# nodes if the cluster is initially scaled down. This was preventing the daemonsets from running if other pods were
# deployed instead. This isn't necessarily an issue if there are many nodes already running which is how we typically
# run clusters. Therefore, this is a dev/ci-cd cluster-only modification.
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: cluster-tool-daemonset-priority
value: 50
globalDefault: false
description: "Make sure cluster-tool daemonsets always get deployed on a busy node"