kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/monitoring?ref=${K8S_GIT_BRANCH}
- prometheus

components:
  - pgo

patchesStrategicMerge:

### Cloud-watch logging and monitoring ###

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cwagentconfig
    namespace: amazon-cloudwatch
  data:
    # Configuration is in Json format. No matter what configure change you make,
    # please keep the Json blob valid.
    cwagentconfig.json: |
      {
        "agent": {
          "region": "${REGION}"
        },
        "logs": {
          "metrics_collected": {
            "kubernetes": {
              "cluster_name": "${CLUSTER_NAME}",
              "metrics_collection_interval": 60
            }
          },
          "force_flush_interval": 5
        }
      }

# NewRelic resources
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nri-bundle-nri-prometheus-config
    namespace: newrelic
  data:
    config.yaml: |
      cluster_name: ${NEW_RELIC_ENVIRONMENT_NAME}
      audit: false
      insecure_skip_verify: false
      require_scrape_enabled_label_for_nodes: true
      scrape_enabled_label: prometheus.io/scrape
      scrape_endpoints: false
      scrape_services: true
      transformations:
      - description: Low data mode defaults
        ignore_metrics:
        - prefixes:
          - kube_
          - container_
          - machine_
          - cadvisor_
      verbose: false

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nri-bundle-nri-kube-events-config
    namespace: newrelic
  data:
    config.yaml: |-
      sinks:
      - name: newRelicInfra
        config:
          agentEndpoint: http://localhost:8001/v1/data
          clusterName: ${NEW_RELIC_ENVIRONMENT_NAME}
          agentHTTPTimeout: 30s

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: newrelic
    name: nri-bundle-nrk8s-agent-controlplane
  data:
    newrelic-infra.yml: |-
      # This is the configuration file for the infrastructure agent. See:
      # https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/
      custom_attributes:
        clusterName: ${NEW_RELIC_ENVIRONMENT_NAME}
      # Report metric data about all the operating system's processes (PDO-4178)
      enable_process_metrics: true
      http_server_enabled: true
      http_server_port: 8001
      is_forward_only: true

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: newrelic
    name: nri-bundle-nrk8s-agent-ksm
  data:
    newrelic-infra.yml: |-
      # This is the configuration file for the infrastructure agent. See:
      # https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/
      custom_attributes:
        clusterName: ${NEW_RELIC_ENVIRONMENT_NAME}
      http_server_enabled: true
      http_server_port: 8002
      is_forward_only: true

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: newrelic
    name: nri-bundle-nrk8s-agent-kubelet
  data:
    newrelic-infra.yml: |-
      # This is the configuration file for the infrastructure agent. See:
      # https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/
      custom_attributes:
        clusterName: ${NEW_RELIC_ENVIRONMENT_NAME}
      features:
        docker_enabled: false
      http_server_enabled: true
      http_server_port: 8003

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: pingmetadata
    namespace: newrelic
  data:
    pingmetadata.yaml: |
      ---
      integrations:
        - name: nri-flex
          interval: 2m
          config:
            name: pingmetadata
            apis:
              - event_type: pingmetaDataOutputSample
                url: http://metadata.${PING_CLOUD_NAMESPACE}:5000
                jq: ".version"

patchesJson6902:

# Newrelic resources
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nri-bundle-nri-metadata-injection
    namespace: newrelic
  patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/CLUSTER_NAME
      value: ${NEW_RELIC_ENVIRONMENT_NAME}

- target:
    group: apps
    version: v1
    kind: Deployment
    name: nri-bundle-nrk8s-ksm
    namespace: newrelic
  patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/CLUSTER_NAME
      value: ${NEW_RELIC_ENVIRONMENT_NAME}

- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: nri-bundle-nrk8s-kubelet
    namespace: newrelic
  patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/CLUSTER_NAME
      value: ${NEW_RELIC_ENVIRONMENT_NAME}

- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: nri-bundle-nrk8s-controlplane
    namespace: newrelic
  patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/CLUSTER_NAME
      value: ${NEW_RELIC_ENVIRONMENT_NAME}

- target:
    group: batch
    version: v1
    kind: Job
    name: newrelic-license-secret-exporter
    namespace: newrelic
  patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/SECRET_NAMESPACE
      value: ${PING_CLOUD_NAMESPACE}

- target:
    group: apps
    version: v1
    kind: Deployment
    name: nri-bundle-newrelic-metadata
    namespace: newrelic
  patch: |-
    - op: replace
      path: /spec/template/metadata/annotations/CLUSTER_NAME
      value: ${NEW_RELIC_ENVIRONMENT_NAME}

- target:
    kind: Service
    name: prometheus
    version: v1
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: prometheus-central.${DNS_ZONE}
