kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    $patch: delete
spec:
  type: ExternalName
  externalName: prometheus-central.${PRIMARY_DNS_ZONE}
  $patch: replace
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: prometheus
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: prometheus
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: prometheus
$patch: delete
---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  namespace: prometheus
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-providers
  namespace: prometheus
$patch: delete
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-dashboards
  namespace: prometheus
$patch: delete
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: prometheus
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: prometheus
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus
$patch: delete
