apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-admin
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-services
        env:
        # PA admin must wait for the PF admin to be ready
        # A space-separated list of deployments or statefulsets that this app should wait for
        - name: WAIT_FOR_SERVICES
          value: pingfederate-cluster