kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/efs-driver?ref=${K8S_GIT_BRANCH}

patchesStrategicMerge:

### Patch to add irsa annotations
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: efs-csi-controller-sa
    annotations:
      purpose: efs-csi-controller
      ${IRSA_PING_ANNOTATION_KEY_VALUE}
