kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingdirectory

resources:
- ../../../../base/pingdirectory/config

configMapGenerator:
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - env_vars