# PingFederate application settings that are shared with both PingFederate Admin and Engine
pingfederate:
  irsaAnnotationKeyValue: "${IRSA_PF_ANNOTATION_KEY_VALUE}"
  podReaperEnabled: "enabled"
  serverProfilePath: "profiles/pingfederate"
  # Note, may can go away once we fix PDO-6879
  kubectlVersion: "v1.30.4"

  license:
    # Only use if you want to provide your own SSM path to perpetual license
    # The default is that automation will determine SSM path to retrieve product license
    overrideProductLicense: ""

# Application settings that is only for PingFederate Admin
pingfederateAdmin:
  pfLogLevel: "INFO"
  verbose: false
  # PingFederate Heap
  pfMinHeap: "256m"
  pfMaxHeap: "512m"
  pfMinYgen: "128m"
  pfMaxYgen: "256m"
  # Individual files should be spelled out, globs are unreliable
  k8sTailLogFiles: "/opt/out/instance/log/jvm-garbage-collection.log /opt/out/instance/log/server.log /opt/out/instance/log/init.log /opt/out/instance/log/admin.log /opt/out/instance/log/admin-event-detail.log /opt/out/instance/log/admin-api.log /opt/out/instance/log/runtime-api.log /opt/out/instance/log/transaction.log /opt/out/instance/log/audit.log /opt/out/instance/log/provisioner-audit.log /opt/out/instance/log/provisioner.log /opt/out/instance/log/request.log /opt/out/instance/log/request2.log"

  # Restore Variables
  restore:
    # Choose desired backup to restore from S3. The default is latest.zip which is the most recent backup.
    backupFileName: ""

    # When deleting PingFederate Admin PVC.
    # Automation will attempt to pull the latest.zip unless specified differently using 'backupFileName' variable.
    # Set 'restoreBackup' to 'false' if you don't want to restore the latest backup from S3.
    restoreBackup: true

    # The following will set PingFederate the minimum and the maximum
    # number of threads used to configure PingFederate thread pools within run.properties.
    # By default, this was designed to be empty and the P1AS automation will
    # dynamically set based on the CPU of the pod. Only override these 2 variables if you truly want to set yourself.
    # 'PF_JETTY_THREADS_MIN' and 'PF_JETTY_THREADS_MAX' is determined for admin.
    pfJettyThreadsMin: ""
    pfJettyThreadsMax: ""

  # Control Ingress Resource for PingFederate Admin
  ingress:
    enableExternalIngress: false
    ingressClassName: "nginx-private"

  # Set container limits for the PingFederate Admin Statefulset
  statefulSet:
    lastUpdateReason: "NA"
    replicas: "1"
    resources:
      limits:
        memory: "4Gi"
        cpu:  "1"
      requests:
        memory: "4Gi"
        cpu: "1"

  # Persistent volume size configuration for PingFederate Admin.
  persistentVolume:
    size: 20Gi
    # Storage provisioner configuration for managing the persistent volume.
    storageProvisioner: "ebs.csi.aws.com"
    # File system type configuration for the persistent volume.
    fsType: "ext4"
    # Storage type configuration for the persistent volume.
    storageType: "gp3"

# Application settings that is only for PingFederate Engine
pingfederateEngine:
  pfLogLevel: "INFO"
  verbose: false
  pfMinHeap: "256m"
  pfMaxHeap: "512m"
  pfMinYgen: "128m"
  pfMaxYgen: "256m"
  # Individual files should be spelled out, globs are unreliable
  k8sTailLogFiles: "/opt/out/instance/log/jvm-garbage-collection.log /opt/out/instance/log/server.log /opt/out/instance/log/init.log /opt/out/instance/log/admin.log /opt/out/instance/log/admin-event-detail.log /opt/out/instance/log/admin-api.log /opt/out/instance/log/runtime-api.log /opt/out/instance/log/transaction.log /opt/out/instance/log/audit.log /opt/out/instance/log/provisioner-audit.log /opt/out/instance/log/provisioner.log /opt/out/instance/log/request.log /opt/out/instance/log/request2.log"
  # Set to true to skip liveness probe.
  skipLiveness: false

  # The following will set PingFederate the minimum and the maximum
  # number of threads used to configure PingFederate thread pools within run.properties.
  # By default, this was designed to be empty and the P1AS automation will
  # dynamically set based on the CPU of the pod. Only override these 2 variables if you truly want to set yourself.
  # 'PF_JETTY_THREADS_MIN' and 'PF_JETTY_THREADS_MAX' is determined for admin.
  pfJettyThreadsMin: ""
  pfJettyThreadsMax: ""

  # Control Ingress Resource for PingFederate Engine
  ingress:
    ingressClassName: "nginx-public"

  # Set container limits for the PingFederate Engine Statefulset
  statefulSet:
    lastUpdateReason: "NA"
    replicas: "2"
    resources:
      requests:
        memory: "4Gi"
        cpu: 2
      limits:
        memory: "4Gi"
        cpu: 2
    podDisruptionBudget:
      minAvailable: "30%"
    hpa:
      minReplicas: 2
      maxReplicas: 2
      averageUtilization: 70

# Outbound provisioning settings
provisioning:
  # Failover grace period in seconds (default: 600)
  pfProvisionerGracePeriod: 600
  # Synchronization frequency in seconds (default: 60)
  pfProvisionerSyncFreq: 60

  # Control settings of k8s custom resource PostgresCluster. Also, known as post-gres-operator|PGO
  postGresCluster:
    ### Execute a PGO database restore for pf-provisioning
    ### To restore database set restoreDatabaseAnnotationKeyValue to "postgres-operator.crunchydata.com/pgbackrest-restore: id1"
    ### ***NOTE: This action will bring down the database until the restoration is complete!***
    ### If this has been executed before, the id number will need to be incremented to kick off a new restore job
    restoreDatabaseAnnotationKeyValue: ""
    replicas: 3
    minAvailable: 1
    resources:
      limits:
        cpu: 2
        memory: "4Gi"
      requests:
        cpu: 2
        memory: "2Gi"
    repo1:
      schedules:
        full: "0 0 * * *"
        differential: "30 */6 * * *"

  # Control the StorageClass settings of PostgresCluster.
  persistentVolume:
    # Storage provisioner configuration for managing the persistent volume.
    storageProvisioner: "ebs.csi.aws.com"
    # File system type configuration for the persistent volume.
    fsType: "ext4"
    # Storage type configuration for the persistent volume.
    storageType: "gp3"

# Periodic CronJob settings for backing up PingFederate Admin
periodicBackupCronJob:
  statefulSet:
    schedule: "30 * * * *"
    resources:
      limits:
        memory: "50Mi"
        cpu: "50m"
      requests:
        memory: "25Mi"
        cpu: "25m"

# Radius Proxy settings
radiusProxy:
  enabled: false

  # Control side-car container within PingFederate statefulset
  statefulSet:
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "500Mi"
        cpu: "400m"

# Heartbeat Exporter settings
heartbeatExporter:

  # Control side-car container within PingFederate statefulset
  statefulSet:
    resources:
      requests:
        memory: "300Mi"
        cpu: "100m"
      limits:
        memory: "300Mi"
        cpu: "100m"

# Delegated Admin settings
delegatedAdmin:
    enabled: true