#
# This defines the httpbin-pa-was deployment.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-httpbin-pa-was
  labels:
    role: healthcheck-httpbin-pa-was
spec:
  selector:
    matchLabels:
      role: healthcheck-httpbin-pa-was
  template:
    metadata:
      name: healthcheck-httpbin-pa-was
      labels:
        role: healthcheck-httpbin-pa-was
    spec:
      containers:
      - name: healthcheck-httpbin-pa-was
        image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "60Mi"
            cpu: "200m"
          requests:
            memory: "10Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 80
---
#
# This service exposes the httpbin-pa-was port to the cluster.
#
apiVersion: v1
kind: Service
metadata:
  name: healthcheck-httpbin-pa-was
  labels:
    role: healthcheck-httpbin-pa-was
spec:
  externalName: healthcheck-httpbin-pa-was.health.svc.cluster.local
  ports:
  - port: 80
    targetPort: 80
  selector:
    role: healthcheck-httpbin-pa-was
