kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: health

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: cluster-health-environment-variables

resources:
- cluster-health.yaml
- pingaccess-health.yaml
- pingaccess-was-health.yaml
- pingdirectory-health.yaml
- pingfederate-health.yaml
- namespace.yaml
- serviceaccount.yaml
- httpbin.yaml
- httpbin-pa-was.yaml
- secrets.yaml
- httpbin-pa.yaml
