apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: healthcheck-user
  namespace: health
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
data:
  HEALTHCHECK_USER_NAME: "aGVhbHRoY2hlY2t1c2Vy"
  HEALTHCHECK_USER_PASSWORD: "aGVhbHRoY2hlY2twYXNzd29yZA=="