apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-healthcheck-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-healthcheck-role
rules:
  - apiGroups:
    - ""
    resources:
    - "nodes"
    - "pods"
    - "pods/log"
    - "secrets"
    - "configmaps"
    - "namespaces"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - "apps"
    resources:
    - "statefulsets"
    - "deployments"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-healthcheck-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-healthcheck-role
subjects:
  - kind: ServiceAccount
    name: cluster-healthcheck-serviceaccount
