kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingcentral

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
