apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate
spec:
  template:
    spec:
      serviceAccountName: ping-serviceaccount
      initContainers:
        - name: wait-for-tls-secret
          $patch: delete
      containers:
        - name: pingcloud-radsecproxy
          $patch: delete
      volumes:
        - name: acme-tls-cert
          $patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: pingfederate
spec:
  ports:
    - port: 2083
      $patch: delete

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pingcloud-radsecproxy-serviceaccount
  namespace: ping-cloud
$patch: delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: radsecproxy-ping-role
  namespace: ping-cloud
$patch: delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radsecproxy-cluster-secrets-reader
  namespace: ping-cloud
$patch: delete

