kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../k8s-configs/ping-cloud

configMapGenerator:

# PingAccess admin
- name: pingaccess-admin-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingaccess/env_vars

# PingAccess engines
- name: pingaccess-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingaccess/env_vars

# PingAccess WAS admin
- name: pingaccess-was-admin-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingaccess-was/env_vars

# PingAccess WAS engines
- name: pingaccess-was-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingaccess-was/env_vars

# PingFederate admin
- name: pingfederate-admin-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingfederate/env_vars

# PingFederate engines
- name: pingfederate-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingfederate/env_vars

# PingDirectory
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingdirectory/env_vars

# Ping Delegated Admin
- name: pingdelegator-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingdelegator/env_vars

# PingCentral
- name: pingcentral-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingcentral/env_vars

# PingDataSync
- name: pingdatasync-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingdatasync/env_vars

# Pingcloud-metadata
- name: pingcloud-metadata-environment-variables
  behavior: merge
  envs:
  - env_vars

# PingCloud-oauth
- name: p14c-oauth-service-environment-variables
  behavior: merge
  envs:
  - env_vars

# PingCloud BOM service
- name: p14c-bom-service-environment-variables
  behavior: merge
  envs:
  - env_vars

# PingCloud P14C bootstrap
- name: pingcloud-p14c-bootstrap-environment-variables
  behavior: merge
  envs:
  - env_vars

patchesJson6902:

# Change the number of pingdirectory replicas to 2 to reduce pressure on the CI/CD pipeline
# and allow more concurrent pipelines.
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pingdirectory
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

# pingcloud-metadata ingress
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: metadata-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: metadata${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: metadata${ENVIRONMENT}.${TENANT_DOMAIN}

# pingdirectory HTTP
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingdirectory-http-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingdirectory${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingdirectory${ENVIRONMENT}.${TENANT_DOMAIN}

# pingfederate runtime
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingfederate-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate${ENVIRONMENT}.${TENANT_DOMAIN}
    # PingFederate global ingress
    - op: add
      path: /spec/tls/0/hosts/-
      value: pf${ENVIRONMENT}.${GLOBAL_TENANT_DOMAIN}
    - op: add
      path: /spec/rules/-
      value:
        host: pf${ENVIRONMENT}.${GLOBAL_TENANT_DOMAIN}
        http:
          paths:
          # This rule gives external access to the global pingfederate runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingfederate
                port:
                  number: 9031

# pingfederate admin api
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingfederate-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate-admin-api${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate-admin-api${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess runtime
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess${ENVIRONMENT}.${TENANT_DOMAIN}
    # PingAccess global ingress
    - op: add
      path: /spec/tls/0/hosts/-
      value: pa${ENVIRONMENT}.${GLOBAL_TENANT_DOMAIN}
    - op: add
      path: /spec/rules/-
      value:
        host: pa${ENVIRONMENT}.${GLOBAL_TENANT_DOMAIN}
        http:
          paths:
          # This rule gives external access to the global pingaccess runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess
                port:
                  number: 443

# pingaccess admin api
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-admin-api${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-admin-api${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess agent
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-agent-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-agent${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-agent${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess was admin
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-was-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-was-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-was-admin${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess was runtime
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-was-ingress
  patch: |-
    # pingaccess admin through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-admin${ENVIRONMENT}.${TENANT_DOMAIN}

    # pingfederate admin through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/1
      value: pingfederate-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/1/host
      value: pingfederate-admin${ENVIRONMENT}.${TENANT_DOMAIN}

    # Grafana through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/2
      value: monitoring${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/2/host
      value: monitoring${ENVIRONMENT}.${TENANT_DOMAIN}

    # Prometheus through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/3
      value: prometheus${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/3/host
      value: prometheus${ENVIRONMENT}.${TENANT_DOMAIN}

    # Kibana through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/4
      value: kibana${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/4/host
      value: logs${ENVIRONMENT}.${TENANT_DOMAIN}

    # Argo CD through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/5
      value: argocd${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/5/host
      value: argocd${ENVIRONMENT}.${TENANT_DOMAIN}

    # PingCentral console through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/6
      value: pingcentral-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/6/host
      value: pingcentral-admin${ENVIRONMENT}.${TENANT_DOMAIN}

# Ping Delegated Admin
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingdelegator-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingdelegator${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingdelegator${ENVIRONMENT}.${TENANT_DOMAIN}

# PingCentral
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingcentral-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingcentral${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingcentral${ENVIRONMENT}.${TENANT_DOMAIN}

# Set a hostname for all the headless services so their endpoint IPs are published to Route53
- target:
    version: v1
    kind: Service
    name: pingdirectory
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdirectory-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

- target:
    version: v1
    kind: Service
    name: pingfederate-cluster
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingfederate-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

- target:
    version: v1
    kind: Service
    name: pingaccess-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingaccess-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

- target:
    version: v1
    kind: Service
    name: pingaccess-was-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingaccess-was-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

# pingdirectory put ldaps on public and change the hostname
- target:
    version: v1
    kind: Service
    name: pingdirectory-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdirectory-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: remove
      path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-internal

# Service that exposes the pingfederate engine radius ports
- target:
    version: v1
    kind: Service
    name: udp-loadbalancer
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingfederate-radius${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: remove
      path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-internal

# pingdatasync put ldaps on public and change the hostname
- target:
    version: v1
    kind: Service
    name: pingdatasync-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdatasync-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: remove
      path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-internal

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: newrelic-license-key
  data:
    NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY_BASE64}

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: topology-descriptor
  data:
    descriptor.json: |-
      ${TOPOLOGY_DESCRIPTOR}
