apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingaccess
spec:
  minReplicas: 2
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pingaccess
  targetCPUUtilizationPercentage: 70
