kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- hpa.yaml
- ingress.yaml
- service.yaml
- statefulset.yaml
- disruption-budget.yaml
