# This service exposes the pingaccess runtime engine and agent ports within cluster.

apiVersion: v1
kind: Service
metadata:
  name: pingaccess
spec:
  ports:
    - port: 443
      name: pingaccess-engine
      targetPort: 3000
    - port: 3030
      name: pingaccess-agent
    - port: 8080
      name: metrics
    - port: 8079
      name: pa-heartbeat
  selector:
    role: pingaccess-engine
