apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: prometheus
spec:
  template:
    spec:
      containers:
        - name: grafana
          resources:
            limits:
              cpu: "400m"
              memory: "2000Mi"
            requests:
              cpu: "100m"
              memory: "1000Mi"