apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was-admin
spec:
  template:
    spec:
      containers:
      - name: pingaccess-was-admin
        resources:
          limits:
            memory: 3Gi
            cpu: 1
          requests:
            memory: 3Gi
            cpu: 1
