apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingdirectory-periodic-backup
$patch: delete

---

