apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/name: nginx-private
    app.kubernetes.io/instance: ingress-nginx-private
    app.kubernetes.io/component: controller
  name: nginx-private
spec:
  controller: k8s.io/ingress-nginx-private
