kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-options: Replace=true

configMapGenerator:
  - name: kibana-alerts-common
    files:
      - 01-log-source.ndjson
  - name: kibana-alerts-pd
    files:
      - 02-pd-rules.ndjson
  - name: kibana-alerts-pds
    files:
      - 03-pds-rules.ndjson
  - name: kibana-alerts-pf
    files:
      - 04-pf-rules.ndjson