# A manual backup job - this does the same thing as the CronJob except it may be configured to be triggered in reaction
# to a ClickOps event.
apiVersion: batch/v1
kind: Job
metadata:
  name: pingfederate-backup
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 5
  template:
    spec:
      serviceAccount: ping-serviceaccount
      restartPolicy: Never
      containers:
      - name: pingfederate-backup
        image: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingfederate:10.3.1-v1.0.16
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
        command:
        - /opt/in/backup-archive-data.sh
        envFrom:
        - configMapRef:
            name: pingfederate-admin-environment-variables
        volumeMounts:
        - name: pingfederate-backup
          mountPath: /opt/in/backup-archive-data.sh
          subPath: backup-archive-data.sh
      volumes:
      - name: pingfederate-backup
        configMap:
          name: pingfederate-backup
          defaultMode: 0555
