apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingfederate-periodic-backup
spec:
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 90
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccount: ping-serviceaccount
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: statefulset.kubernetes.io/pod-name
                    operator: In
                    values:
                    - "pingfederate-admin-0"
                topologyKey: "kubernetes.io/hostname"
          restartPolicy: OnFailure
          containers:
          - name: pingfederate-backup
            image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-apps/pingfederate:test-pf-2
            imagePullPolicy: Always
            securityContext:
              runAsGroup: 9999
              runAsNonRoot: true
              runAsUser: 9031
              allowPrivilegeEscalation: false
            command:
            - /opt/in/backup-archive-data.sh
            envFrom:
            - configMapRef:
                name: pingfederate-admin-environment-variables
            - configMapRef:
                name: pingcommon-environment-variables
            env:
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
            volumeMounts:
            - name: pingcommon-backup
              mountPath: /opt/in/backup-archive-data.sh
              subPath: backup-archive-data.sh
          volumes:
          - name: pingcommon-backup
            configMap:
              name: pingcommon-backup
              defaultMode: 0555
