apiVersion: v1
kind: ConfigMap
metadata:
  name: pingfederate-backup
data:
  backup-archive-data.sh: |-
    #!/bin/sh

    # Install kubectl
    curl -sS https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl \
    -o /tmp/kubectl
    
    chmod +x /tmp/kubectl

    UPLOAD_FILES=
    SERVER=$(/tmp/kubectl get pod -l role=${K8S_DEPLOYMENT_NAME_PINGFEDERATE_ADMIN} | sed -n "/${K8S_DEPLOYMENT_NAME_PINGFEDERATE_ADMIN}/p" | awk '{print $1}')
    SCRIPT="${HOOKS_DIR}"/90-upload-backup-s3.sh
    LOG_FILE=/tmp/upload.log

    echo "Uploading pingfederate backup data on server ${SERVER}"
    /tmp/kubectl exec "${SERVER}" -c pingfederate-admin -- sh -c "test -x ${SCRIPT} && ${SCRIPT}" >"${LOG_FILE}"

    if test ${?} -eq 0; then
      # Sending logs to STDOUT
      cat ${LOG_FILE}
      UPLOAD_FILE=$(tail -1 "${LOG_FILE}")
      test -z "${UPLOAD_FILES}" && UPLOAD_FILES="${UPLOAD_FILE}" || UPLOAD_FILES="${UPLOAD_FILES} ${UPLOAD_FILE}"
    else
      echo "Upload script not found on server ${SERVER}"
    fi

    # Print the names of the uploaded files so callers know exactly what was uploaded
    echo "The following files were uploaded:"
    echo "${UPLOAD_FILES}"
---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingfederate-periodic-backup
spec:
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: ping-serviceaccount
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: statefulset.kubernetes.io/pod-name
                    operator: In
                    values:
                    - "pingfederate-admin-0"
                topologyKey: "kubernetes.io/hostname"
          restartPolicy: OnFailure
          containers:
          - name: pingfederate-backup
            image: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingfederate:10.3.1-v1.0.16
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsGroup: 9999
              runAsNonRoot: true
              runAsUser: 9031
            command:
            - /opt/in/backup-archive-data.sh
            envFrom:
            - configMapRef:
                name: pingfederate-admin-environment-variables
            volumeMounts:
            - name: pingfederate-backup
              mountPath: /opt/in/backup-archive-data.sh
              subPath: backup-archive-data.sh
          volumes:
          - name: pingfederate-backup
            configMap:
              name: pingfederate-backup
              defaultMode: 0555
