apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingfederate-admin-periodic-csd-upload
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 90
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccount: ping-serviceaccount
          restartPolicy: OnFailure
          containers:
          - name: pingfederate-admin-periodic-csd-upload
            image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-apps/pingfederate:test-pf-2
            imagePullPolicy: Always
            securityContext:
              runAsGroup: 9999
              runAsNonRoot: true
              runAsUser: 9031
              allowPrivilegeEscalation: false
            command:
            - /opt/in/backup-csd-data.sh
            env:
            - name: CSD_POD_ROLE
              value: "pingfederate-admin"
            - name: CSD_CONTAINER_NAME
              value: "pingfederate-admin"
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: "true"
            envFrom:
            - configMapRef:
                name: pingfederate-admin-environment-variables
            - configMapRef:
                name: pingcommon-environment-variables
            volumeMounts:
            - name: pingfederate-periodic-csd-upload
              mountPath: /opt/in/backup-csd-data.sh
              subPath: backup-csd-data.sh
          volumes:
          - name: pingfederate-periodic-csd-upload
            configMap:
              name: pingfederate-periodic-csd-upload
              defaultMode: 0555
