apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
  labels:
    app: logstash-elastic
data:
  pipelines.yml: |
    - pipeline.id: main
      path.config: "/usr/share/logstash/pipeline/main"
    - pipeline.id: customer
      path.config: "/usr/share/logstash/pipeline/customer"
    - pipeline.id: alerts
      path.config: "/usr/share/logstash/pipeline/alerts"