kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base
- custom-resources

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:

# Pingdirectory
# Create the config maps that hold the variable for triggering updates of PD servers
- name: pingdirectory-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingdirectory/env_vars

# Merge all env_vars into Pingdirectory common environment variables configmap
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingdirectory/env_vars


# Pingfederate
# Create the config maps that hold the variable for triggering updates of PF servers
- name: pingfederate-admin-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingfederate/admin/env_vars

- name: pingfederate-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingfederate/engine/env_vars

# Merge all env_vars into Pingfederate environment variables configmaps
- name: pingfederate-admin-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingfederate/admin/env_vars

- name: pingfederate-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingfederate/engine/env_vars


# PingAccess
# Create the config maps that hold the variable for triggering updates of PA servers
- name: pingaccess-admin-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingaccess/admin/env_vars

- name: pingaccess-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingaccess/engine/env_vars

# Merge all env_vars into PingAccess environment variables configmaps
- name: pingaccess-admin-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingaccess/admin/env_vars

- name: pingaccess-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingaccess/engine/env_vars


# PingAccess WAS
# Create the config maps that hold the variable for triggering updates of PA WAS servers
- name: pingaccess-was-admin-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingaccess-was/admin/env_vars

- name: pingaccess-was-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingaccess-was/engine/env_vars

# Merge all env_vars into PingAccess WAS environment variables configmaps
- name: pingaccess-was-admin-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingaccess-was/admin/env_vars

- name: pingaccess-was-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingaccess-was/engine/env_vars


# PingDelegator
# Create the config maps that hold the variable for triggering updates of DA servers
- name: pingdelegator-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingdelegator/env_vars

# Ping Delegated Admin
- name: pingdelegator-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingdelegator/env_vars


# PingCloud services
# Pingcloud-metadata
- name: pingcloud-metadata-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars

# PingCloud-oauth
- name: p14c-oauth-service-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

# PingCloud BOM service
- name: p14c-bom-service-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

# PingCloud P14C bootstrap
- name: pingcloud-p14c-bootstrap-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars

patchesStrategicMerge:

### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
- custom-patches.yaml

### Regional enablement - remove admins, backups, etc. from secondary ###
### These patches should be commented out on the primary region ###

- ../base/ping-cloud/pingdirectory/server/remove-from-secondary-patch.yaml

- ../base/ping-cloud/pingaccess-was/admin/remove-from-secondary-patch.yaml
- ../base/ping-cloud/pingaccess-was/engine/remove-from-secondary-patch.yaml

- ../base/ping-cloud/pingfederate/admin/remove-from-secondary-patch.yaml
- ../base/ping-cloud/pingaccess/admin/remove-from-secondary-patch.yaml

- ../base/ping-cloud/pingcommon/my-ping/remove-from-secondary-patch.yaml
