kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- ../cloud-generic
#- periodic-csd-upload.yaml

patchesStrategicMerge:
- discovery-service.yaml
