---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enrichment-elasticsearch-ilm-policies
data:
  ping-7-day-retention.json: |
    {
        "policy": {                      
            "phases": {
                "hot": {                     
                    "actions": {
                        "rollover": {            
                            "max_age": "1d"
                        }
                    }
                },
                "delete": {
                    "min_age": "7d",          
                    "actions": {
                        "delete": {}             
                    }
                }
            }
        }
    }
  ping-logstash-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "1d"
              },
              "set_priority": {
                "priority": 100
              }
            }
          },
          "warm": {
            "min_age": "90d",
            "actions": {
              "forcemerge": {
                "max_num_segments": 1,
                "index_codec": "best_compression"
              },
              "readonly": {},
              "set_priority": {
                "priority": 50
              },
              "shrink": {
                "number_of_shards": 1
              },
              "allocate": {
                "number_of_replicas": 0
              }
            }
          },
          "delete": {
            "min_age": "270d",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }

  alerts.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "set_priority": {
                "priority": 100
              },
              "rollover": {
                "max_age": "1d"
              }
            }
          },
          "warm": {
            "min_age": "7d",
            "actions": {
              "forcemerge": {
                "max_num_segments": 1
              },
              "readonly": {},
              "set_priority": {
                "priority": 50
              },
              "shrink": {
                "number_of_shards": 1
              }
            }
          },
          "delete": {
            "min_age": "30d",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }