---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enrichment-elasticsearch-ilm-policies
data:
  ping-2-day-retention.json: |
    {
        "policy": {                      
            "phases": {
                "hot": {                     
                    "actions": {
                        "rollover": {            
                            "max_size": "2GB"
                        }
                    }
                },
                "delete": {
                    "min_age": "2d",          
                    "actions": {
                        "delete": {}             
                    }
                }
            }
        }
    }

  ping-7-day-retention.json: |
    {
        "policy": {                      
            "phases": {
                "hot": {                     
                    "actions": {
                        "rollover": {            
                            "max_size": "8GB"
                        }
                    }
                },
                "delete": {
                    "min_age": "7d",          
                    "actions": {
                        "delete": {}             
                    }
                }
            }
        }
    }
  ping-logstash-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_age": "1d"
              }
            }
          },
          "delete": {
            "min_age": "30d",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
