kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- elasticsearch-ilm-policies.yaml
- enrichment-cache.yaml
- logstash-search-templates.yaml
- kibana-alerts
- index-templates