---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enrichment-logstash-search-templates
data:
  6hr-1200km-template.json: |
    {
    "query": {
        "bool": {
        "must": [],
        "filter": [
            {
            "bool": {
                "filter": [
                {
                    "bool": {
                    "filter": [
                        {
                        "range": {
                            "@timestamp": {
                            "gte": "now-6h/h",
                            "lte": "now"
                            }
                        }
                        },
                        {
                        "bool": {
                            "should": [
                            {
                                "match": {
                                "status": "success"
                                }
                            }
                            ],
                            "minimum_should_match": 1
                        }
                        },
                        {
                        "bool": {
                            "should": [
                            {
                                "match": {
                                "event": "AUTHN_ATTEMPT"
                                }
                            }
                            ],
                            "minimum_should_match": 1
                        }
                        },
                        {
                        "bool": {
                            "should": [
                            {
                                "match": {
                                "subject": "\"%{[subject]}\""
                                }
                            }
                            ],
                            "minimum_should_match": 1
                        }
                        }
                    ]
                    }
                }
                ]
            }
            }
        ],
        "should": [],
        "must_not" : {
            "geo_distance" : {
                "distance" : "1200km",
                "geoip.location" : {
                    "lat"  : "%{[geoip][location][lat]}",
                    "lon"  : "%{[geoip][location][lon]}" 
                }
            }
        }
        }
    },
    "size" : 1,
    "sort": [
        {
        "@timestamp": {
            "order": "desc"
        }
        }
    ],
    "_source": ["subject", "geoip.location.lat", "geoip.location.lon", "geoip.country_name","geoip.city_name", "protocol", "ip", "malicious_country", "suspicious_country", "_id" ]  
    }
