kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../../../base/ingress/nginx/public

patchesStrategicMerge:
- |-
  apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: nginx-ingress-controller
  spec:
    minReplicas: 3
    maxReplicas: 5