# The minimal bootstrap required to avoid crash loop of the ping-cloud stack.
# If the SSH secret and known_hosts configmap are not not deployed before the pods, the pods will crash forever.

apiVersion: v1
kind: Namespace
metadata:
  name: ${PING_CLOUD_NAMESPACE}
  labels:
    app: ${PING_CLOUD_NAMESPACE}

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
  namespace: ${PING_CLOUD_NAMESPACE}
data:
  id_rsa: |
    ${SSH_ID_KEY_BASE64}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: known-hosts-config
  namespace: ${PING_CLOUD_NAMESPACE}
data:
  known_hosts: |
    ${KNOWN_HOSTS_CLUSTER_STATE_REPO}