### Feature flag - Uncomment this file to enable Postgres Operator (PGO)
# kind: Kustomization
# apiVersion: kustomize.config.k8s.io/v1beta1

# resources:
# - ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/pgo/base?ref=${K8S_GIT_BRANCH}