apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12999
        targetPort: 12999
        name: notification
      - port: 13000
        targetPort: 13000
        name: prometheus
  webhook:
    notification:
      port: "12999"
      endpoint: /notification
      method: POST
    prometheus:
      port: "13000"
      endpoint: /notification
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: trigger-slack
    eventSourceName: webhook
    eventName: notification
  triggers:
    - template:
        name: trigger-slack
        slack:
          channel: p1as-application-oncall
          message: this is default message from argo-events
          slackToken:
            key: token
            name: slack-secret
      parameters:
        - src:
            dependencyName: trigger-slack
            dataKey: body.channel
          dest: slack.channel
        - src:
            dependencyName: trigger-slack
            dataKey: body.message
          dest: slack.message
---
# Dummy token, it will be replaced by platform injected token.
apiVersion: v1
kind: Secret
metadata:
  name: slack-secret
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
data:
  token: QkFTRTY0LUVOQ09ERUQtT0FVVEgtVE9LRU4=

