# For reference, please see the documentation in the root of the repo docs/StorageClass.md
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-csi-sc1
  labels:
    app: elasticsearch
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  encrypted: "true"
  type: sc1
mountOptions:
  - discard
