### Argo CD ###

# Deploy the git key of the CD tool to the cluster state repo
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argo-git-deploy
  namespace: argocd
data:
  identity: |
    ${SSH_ID_KEY_BASE64}

---

# Add argocd admin password to the data section with the bcrypt hash value.
# Ref: https://argo-cd.readthedocs.io/en/stable/faq/#i-forgot-the-admin-password-how-do-i-reset-it
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
data:
  admin.password: "JDJhJDEwJHlWRU5GT21mTzBGcXNLNlVreTBEei5vLzM1ekloWDdmMjBvOU9CRVFKNVZqWUpOUHhGbUNlCg=="

---

### Ping app SSH private key ###

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    ${SSH_ID_KEY_BASE64}

---

### Argo CD Image Updater  ###

# Deploy the git key for argocd-image-updater
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-image-updater-ssh-key
  namespace: argocd
data:
  sshPrivateKey: |
    ${SSH_ID_KEY_BASE64}

---

#Argocd slack token

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-notifications-secret
data:
  slack-token: ${ARGOCD_SLACK_TOKEN_BASE64}

---

# Add argocd admin password for argocd-image-updater.
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
data:
  argocd.token: "JDJhJDEwJHlWRU5GT21mTzBGcXNLNlVreTBEei5vLzM1ekloWDdmMjBvOU9CRVFKNVZqWUpOUHhGbUNlCg=="

---

# Slack token to send argo events notification
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-secret
  namespace: argo-events
data:
  token: ${ARGOCD_SLACK_TOKEN_BASE64}

---

# NewRelic license key to send APM data
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: newrelic-license-key
data:
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY_BASE64}

---

# In order to change the PingCentral admin password, 2 rollouts are necessary. 
#
# 1. On the 1st rollout, change the PC_ADMIN_USER_PASSWORD as appropriate and the 
#    LAST_UPDATE_REASON for PingCentral. This will cause a rollout/restart of
#    the PingCentral pod.
# 2. On the 2nd rollout, change the OLD_PC_ADMIN_USER_PASSWORD to match the 
#.   PC_ADMIN_USER_PASSWORD. This will cause an update of the secret. 
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcentral-passwords

---

### Licenses ###

# Add pingcentral.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingcentral-license
type: Opaque

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nr-license-key
  namespace: elastic-stack-logging
data:
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY_BASE64}

---

### Product passwords ###

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD,
#                                    P14C_ISSUER, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-was-passwords
