apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: pingdirectory
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 4Gi
            cpu: 2
      - name: stunnel
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 300m
      - name: pingdirectory-statsd-exporter
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-gp2
      resources:
        requests:
          storage: 50Gi