kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- daemonset.yaml
- deployment.yaml
- job.yaml
- mutationwebhookconfiguration.yaml
- service.yaml
- serviceaccount.yaml