---
# Source: nri-bundle/charts/nri-metadata-injection/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: nri-bundle-nri-metadata-injection
  namespace: newrelic
  labels:
    nri-bundle.version: 5.0.4
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/name: nri-metadata-injection
    app.kubernetes.io/version: 1.7.0
    helm.sh/chart: nri-metadata-injection-3.0.4
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/name: nri-metadata-injection

---
# Source: nri-bundle/charts/kube-state-metrics/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: nri-bundle-kube-state-metrics
  namespace: newrelic
  labels:
    nri-bundle.version: 5.0.4
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-4.23.0
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/managed-by: Helm
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: "ClusterIP"
  ports:
  - name: "http"
    protocol: TCP
    port: 8080
    targetPort: 8080
  
  selector:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: nri-bundle
