apiVersion: v1
kind: ConfigMap
metadata:
  name: pf-exporter-config
data:
  config.yml: |-
    ---
    metrics:
    - name: metric_pingfederate_idp_session_registry_session_map_size
      path: '{.idp\.session\.registry\.session\.map\.size}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_response_concurrency_statistics_90_percentile
      path: '{.response\.concurrency\.statistics\.90\.percentile}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_response_statistics_count
      path: '{.response\.statistics\.count}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_response_time_statistics_90_percentile
      path: '{.response\.time\.statistics\.90\.percentile}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_session_state_attribute_map_size
      path: '{.session\.state\.attribute\.map\.size}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_sp_session_registry_session_map_size
      path: '{.sp\.session\.registry\.session\.map\.size}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_total_failed_transactions
      path: '{.total\.failed\.transactions}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_total_transactions
      path: '{.total\.transactions}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_response_concurrency_statistics_mean
      path: '{.response\.concurrency\.statistics\.mean}'
      labels:
        environment: pingfederate
        source: heartbeat
    - name: metric_pingfederate_response_time_statistics_mean
      path: '{.response\.time\.statistics\.mean}'
      labels:
        environment: pingfederate
        source: heartbeat

---