kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- enrichment
- namespace.yaml
- kibana
- logstash
- elasticsearch

configMapGenerator:
- name: elk-environment-variables
  envs:
  - env_vars