apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token
  template.app-health-degraded: |
    slack:
      attachments: |
        [{
          "title": "{{ .app.metadata.name}} - Health Degraded",
          "color": "#f4c030",
          "fields": [
            { "Title": "Health status",
              "value": "{{.app.status.health.status}}",
              "short": true
            },
            {
              "title": "Current Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Last Sync Result",
              "value": "{{.app.status.operationState.phase}}",
              "short": true
            }
          ]
        }]
  template.app-sync-failed: |
    slack:
      attachments: |
        [{
          "title": "{{ .app.metadata.name}} - Last Sync Failed",
          "color": "#E96D76",
          "fields": [
            {
              "title": "Current Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Last Sync Result",
              "value": "{{.app.status.operationState.phase}}",
              "short": true
            }
          ]
        }]
  template.app-sync-status-unknown: |
    slack:
      attachments: |
        [{
          "title": "{{ .app.metadata.name}} - Sync status unknown, sync did not work!",
          "color": "#E96D76",
          "fields": [
            {
              "title": "Current Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Last Sync Result",
              "value": "{{.app.status.operationState.phase}}",
              "short": true
            }
          ]
        }]
  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send:
      - app-sync-status-unknown
      when: app.status.sync.status == 'Unknown'
