kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud

resources:
- secret-license.yaml
- secret-passwords.yaml
- configmap-csd-upload.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingaccess-was-admin-environment-variables
  envs:
  - env_vars

- name: pingaccess-was-environment-variables
  envs:
  - env_vars
