kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- config
- admin
- engine
# Provisioning, while added here, is manually uncommented only if enabled
- provisioning
- ff-external-ingress