apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate
spec:
  template:
    spec:
      containers:
      - name: pingfederate
        resources:
          limits:
            memory: "4Gi"
            cpu: 2
          requests:
            memory: "4Gi"
            cpu: 2
