# For more information on prometheus configuration go to https://prometheus.io/docs/prometheus/latest/configuration/configuration/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
spec:
  serviceName: prometheus
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: public.ecr.aws/r2h3l6e4/pingcloud-clustertools/prom/prometheus:v2.42.0
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.retention.time=$(PROMETHEUS_RETENTION_TIME)"
          - "--web.enable-remote-write-receiver"
          - "--enable-feature=memory-snapshot-on-shutdown"
          - "--enable-feature=expand-external-labels"
          - "--enable-feature=memory-snapshot-on-shutdown"
        env:
          - name: PROMETHEUS_RETENTION_TIME
            valueFrom:
              configMapKeyRef:
                key: PROMETHEUS_RETENTION_TIME
                name: prometheus-environment-variables
        envFrom:
          - configMapRef:
              name: prometheus-environment-variables
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/
          - name: prometheus-storage-volume
            mountPath: /prometheus/data
          - name: alertsconfig
            mountPath: /etc/prometheus/alert-rules.d

        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 1500m
            memory: 5500Mi
          requests:
            cpu: 100m
            memory: 2000Mi
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      - name: alertsconfig
        configMap:
          name: prom-alerts

  volumeClaimTemplates:
  - metadata:
      name: prometheus-storage-volume
      labels:
        app: prometheus
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: efs
      resources:
        requests:
          storage: 1Mi

---

kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prometheus-central-dev.ping-demo.com
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    name: prometheus
  clusterIP: None

---

# Define role which allows access to endpoint /metrics within the cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
- apiGroups: [ "" ]
  resources: [ "pods/exec" ]
  verbs: [ "create" ]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: prometheus

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: prometheus

