apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-gp3
parameters:
  type: gp3
  encrypted: "true"
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer