kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply PingAccess runtime engine deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingaccess/engine?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess
  newTag: ${PINGACCESS_IMAGE_TAG}

patchesJson6902:

### PingAccess Engine Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pingaccess
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingaccess-last-update-config

### Ingress patches ###

# pingaccess runtime
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess.${DNS_ZONE}
    # PingAccess global ingress
    - op: add
      path: /spec/tls/0/hosts/-
      value: pa.${ENV}.${GLOBAL_TENANT_DOMAIN}
    - op: add
      path: /spec/rules/-
      value:
        host: pa.${ENV}.${GLOBAL_TENANT_DOMAIN}
        http:
          paths:
          # This rule gives external access to the global pingaccess runtime service
          - pathType: Prefix
            path: /
            backend:
              service:
                name: pingaccess
                port:
                  number: 443

# pingaccess agent
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-agent-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-agent.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-agent.${DNS_ZONE}
