kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argocd

resources:
  - ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/git-ops?ref=${K8S_GIT_BRANCH}
  - argocd-application-set.yaml

patchesStrategicMerge:
  - argocd-strategic-patches.yaml

patchesJson6902:
  ### Cluster state repo URL and auth configuration for the CD tool ###
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    path: argocd-cm-patch.yaml

configMapGenerator:
  - name: argocd-bootstrap
    namespace: argocd
    behavior: merge
    envs:
      - env_vars
    options:
      disableNameSuffixHash: true
