kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

configMapGenerator:
  - name: enrichment-elasticsearch-index-templates
    files:
      - alerts.json
      - backup-jobs.json
      - healthchecks.json
      - logstash.json
      - pa-admin-audit.json
      - pa-admin-system.json
      - pa-audit.json
      - pa-system.json
      - pa-was-admin-audit.json
      - pa-was-admin-system.json
      - pa-was-audit.json
      - pa-was-system.json
      - pd-access.json
      - pd-failed-ops.json
      - pf-admin-audit.json
      - pf-admin-system.json
      - pf-audit.json
      - pf-provision.json
      - pf-requests.json
      - pf-system.json
      - pf-transaction.json