apiVersion: v1
kind: ConfigMap
metadata:
  name: pa-exporter-config
data:
  config.yml: |-
    ---
    metrics:
    - name: metric_pingaccess_response_concurrency_statistics_90_percentile
      path: '{.response\.concurrency\.statistics\.90\.percentile}'
      labels:
        environment: pingaccess
        source: heartbeat
    - name: metric_pingaccess_response_statistics_count
      path: '{.response\.statistics\.count}'
      labels:
        environment: pingaccess
        source: heartbeat
    - name: metric_pingaccess_response_time_statistics_90_percentile
      path: '{.response\.time\.statistics\.90\.percentile}'
      labels:
        environment: pingaccess
        source: heartbeat
    - name: metric_pingaccess_response_concurrency_statistics_mean
      path: '{.response\.concurrency\.statistics\.mean}'
      labels:
        environment: pingaccess
        source: heartbeat
    - name: metric_pingaccess_response_time_statistics_mean
      path: '{.response\.time\.statistics\.mean}'
      labels:
        environment: pingaccess
        source: heartbeat

---