apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdatasync-backup
data:
  backup-sync-state.sh: |-
    #!/bin/sh
    set -e

    # Install kubectl
    curl -sS https://storage.googleapis.com/kubernetes-release/release/"${KUBECTL_VERSION}"/bin/linux/amd64/kubectl \
    -o /tmp/kubectl

    chmod +x /tmp/kubectl

    UPLOAD_FILES=
    SCRIPT="${HOOKS_DIR}"/15-upload-sync-state-s3.sh
    LOG_FILE=/tmp/upload.log

    SERVER=$(/tmp/kubectl get pod -l class=pingdatasync-server -o jsonpath="{.items[0].metadata.name}")

    echo "Running backup script within ${SERVER} pod"

    /tmp/kubectl exec "${SERVER}" -c pingdatasync -- sh -c "test -x ${SCRIPT} && ${SCRIPT}"> "${LOG_FILE}"

    if test ${?} -eq 0; then
      UPLOAD_FILE=$(tail -1 "${LOG_FILE}")
      test -z "${UPLOAD_FILES}" && UPLOAD_FILES="${UPLOAD_FILE}" || UPLOAD_FILES="${UPLOAD_FILES} ${UPLOAD_FILE}"
    else
      echo "Upload script not found on pod ${SERVER}"
    fi

    echo "${UPLOAD_FILES}"

---

# A manual backup job to backup config/sync-state.ldif - it may be configured to be triggered in reaction
# to a ClickOps event.
apiVersion: batch/v1
kind: Job
metadata:
  name: pingdatasync-backup
  labels:
    app: ping-cloud
    role: pingdatasync
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 5
  template:
    spec:
      serviceAccount: ping-serviceaccount
      restartPolicy: Never
      containers:
      - name: pingdatasync-backup
        image: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingdatasync/dev:v1.18-release-branch-latest
        imagePullPolicy: Always
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
          allowPrivilegeEscalation: false
        command:
        - /opt/in/backup-sync-state.sh
        envFrom:
        - configMapRef:
            name: pingdatasync-environment-variables
        - configMapRef:
            name: pingcommon-environment-variables
        volumeMounts:
        - name: backup-script
          mountPath: /opt/in/backup-sync-state.sh
          subPath: backup-sync-state.sh
      volumes:
      - name: backup-script
        configMap:
          name: pingdatasync-backup
          defaultMode: 0555
