apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: "1000"
      memory: 1000Gi
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  providerRef:
    name: default
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: pd-only
spec:
  annotations:
    karpenter.sh/do-not-consolidate: "true"
  limits:
    resources:
      cpu: "1000"
      memory: 1000Gi
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  taints:
  - effect: NoSchedule
    key: pd-only
  providerRef:
    name: pd-only
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  tags:
    KarpenerProvisionerName: "default"
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: pd-only
spec:
  tags:
    KarpenerProvisionerName: "pd-only"
