kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: logstash-pipeline-alerts
  files:
    - 01-input.conf
    - 02-filters.conf
    - 03-output.conf
