kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/karpenter

patchesStrategicMerge:
- |-
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: default
  spec:
    requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]
