kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base
- custom-resources 

generatorOptions:
  disableNameSuffixHash: false

patchesStrategicMerge:

### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
- custom-patches.yaml

configMapGenerator:

# PingCentral
# Create the config maps that hold the variable for triggering updates of PingCentral
- name: pingcentral-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingcentral/env_vars

# Merge all env_vars into PingCentral common environment variables configmap
- name: pingcentral-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingcentral/env_vars


# PingCloud services
# Pingcloud-metadata
- name: pingcloud-metadata-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
