apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: prometheus
spec:
  template:
    spec:
      containers:
        - name: grafana
          resources:
            limits:
              cpu: "1000m"
              memory: "3000Mi"
            requests:
              cpu: "300m"
              memory: "2500Mi"