kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:

# These yamls were obtained from: https://api.github.com/repos/kubernetes-sigs/metrics-server/releases/latest
- aggregated-metrics-reader.yaml
- auth-delegator.yaml
- auth-reader.yaml
- metrics-apiservice.yaml
- metrics-server-deployment.yaml
- metrics-server-service.yaml
- resource-reader.yaml
